### ISSUE TITLE
Please Display 4 Numerical Values on Icon (do not display decimal -- read explanation below please)

### ISSUE THREAD

**Issue by vdisclafani** [nfl0/Bitcoin-lightweight-ticker#1]
Love this extension because very few tickers display a Crypto value without clicking on the icon !  
You have improved on Alexandre Oliveira's ticker, which only displayed 2 digits (far too little precision to be useful).
HOWEVER,why not stop displaying the decimal and use all four 'places' to display numerical values, 
with the understanding (of the user) that they must use another extension that, for example, has a popup or dropdown box for absolute confirmation that BTC has not dropped in price to 4 digits USD of value, or risen to 6 digits USD (left of decimal).  
(Perhaps you wish to add a popup or dropdown box to display the true (complete) BTC value to your extension -- that would be awesome!)
Anyone with any knowledge whatsoever of the Bitcoin market (ie. anyone who would be interested in an extension constantly displaying a BTC in their browser toolbar) would accurately assume that a BTC icon displaying '1175' for BTC almost certainly means $ 11,750  NOT $1,750  (unless the Apocalypse has come, or we have been invaded by Aliens from Planet 9, at which point Plan B for Earthlings is definitely of more interest than the current BTC price, ha!).
On a serious note, for an BTC investor (or anyone who holds BTC) , there is a lot of difference between a BTC icon display price of 1170 ($11,700.) ranging to 1179 ($11,790.) insofar as the displayed value necessitates an action to buy or sell BTC.   Knowing whether to buy or sell BTC 'at a glance' (from the 4 place numerical BTC icon value) would truly increase the value of the extension for me, and I think for any user of your extension.
Thank you for listening, and for your selflessness in programming for the public -- I admire you!  
Victoria
(Victoria Di Sclafani, MPH, PhD -- retired; neuroscience research Yale Med School)
P.S.  Should you decide to accept this mission, ha!, I will surely be pushing a little BTC your way...

**Comment by nfl0** [comment]
https://addons.mozilla.org/en-US/firefox/addon/btc/

**Comment by nfl0** [comment]
Just Bitcoin Ticker [PRO] v2.0.0

* The price display on the icon can now be toggled between Abbreviated (13k) and Four digit value (1317)
* Colored price movement indicator feature
* Bug fixes and performance improvements

**Comment by vdisclafani** [comment]
Hello [n22dl2](https://addons.mozilla.org/en-US/firefox/user/15420874/)!
I gave your BTC ticker a stellar review -- please read it!  I have gone through SO many 'constant display' toolbar tickers that waste a 'space' on a decimal -- a big loss in precision, particularly whenthe crypto is expensive ( like BTC). The color coding of background for rise or fall of price is a simple idea, but I've never come across this function in this type of a ticker either (nor did the idea occur to me!).
Thank you so much for emailing me or I wouldn't have realized the 'toggle' option. I will remember to read the add-on descriptions better!

Victoria
Dr. Di Sclafani
Sent with [ProtonMail](https://protonmail.com/?utm_campaign=ww-all-2a-mail-pmm_mail-protonmail_signature&utm_source=proton_users&utm_medium=cta&utm_content=sent_with_protonmail_secure_email) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
